[unstable]
# cross compile core library for custom target
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]


[build]
rustflags = ["--emit=asm"]
# points to file in project root
target = "i386-unknown.json"
