
[package]
name = "os-in-rust"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
volatile = "0.2.6"
spin = "0.5.2"
bootloader = "0.9.8"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
